# Generated by Django 5.0.2 on 2024-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='form_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
