# Generated by Django 5.0.2 on 2024-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0003_remove_contactform_form_content_contactformcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='to_sent',
            field=models.CharField(max_length=2000),
        ),
    ]
