# Generated by Django 5.0.2 on 2024-05-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0004_alter_contactform_to_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
