# Generated by Django 5.0.2 on 2024-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0005_contactform_message_contactform_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformcontent',
            name='ip_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
