# Generated by Django 5.0.2 on 2024-05-16 04:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_contactform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactForms',
        ),
    ]
